image: debian:bullseye

stages:
  - deploy

deploy_to_production:
  stage: deploy
  script:
    - apt update && apt install -y sshpass
    - sshpass -p "$andrey_sp_password" ssh -v andrey_sp@94.131.121.166 "sudo -i && cd /root/tinderone/admin-panel && git pull origin main && ./admin_panel_update.sh"
  only:
    - main
