image: debian:bullseye

before_script:
  - apt-get update && apt-get install -y openssh-client

stages:
  - deploy

deploy_to_production:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 94.131.121.166 >> ~/.ssh/known_hosts
    - ssh root@94.131.121.166 "cd /root/tinderone/admin-panel && git pull origin main && docker-compose down && docker-compose up -d && docker exec admin_panel_laravel bash -c "php artisan view:clear && php artisan route:clear && php artisan cache:clear && php artisan config:cache && npm install && npm run build" "
  only:
    - main
