image: debian:bullseye

before_script:
  - apt-get update && apt-get install -y openssh-client php-cli

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo -e "$GITLAB_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 176.118.167.210 >> ~/.ssh/known_hosts
    - ssh-keyscan -H 176.118.167.118 >> ~/.ssh/known_hosts
    - ssh root@176.118.167.210 "cd /var/www/admin.tinderone.ru && ./deploy.sh"
    - ssh root@176.118.167.210 "cd /var/www/api.tinderone.app && ./deploy.sh"
    - ssh root@176.118.167.118 "cd /var/www/api.tinderone.app && ./deploy.sh"
  only:
    - main
